const seedColors = [
  {
    paletteName: 'Caleb Widowghast Colors',
    id: 'caleb-widowghast-colors',
    emoji: '🔥',
    colors: [
      { name: 'WisdomSave', color: '#f88644' },
      { name: 'VaultOfAmber', color: '#ab6b3f' },
      { name: 'BookPage', color: '#867468' },
      { name: 'FormerTeacher', color: '#d3d2d5' },
      { name: 'Polymorph', color: '#9a4ae2' },
      { name: 'Home', color: '#ff6700' },
      { name: 'CatsIre', color: '#703524' },
      { name: 'SpellBook', color: '#5a3b2a' },
      { name: 'Dunamancy', color: '#868a99' },
      { name: 'Essek', color: '#6e4b6e' },
      { name: 'WidowghastsWebOfFire', color: '#e91f0f' },
      { name: 'Leomands', color: '#492620' },
      { name: 'Frumpkin', color: '#573823' },
      { name: 'DeepRegret', color: '#3f3936' },
      { name: 'NineSidedTower', color: '#421e2a' },
      { name: 'EmipreKid', color: '#631e1e' },
      { name: 'DirtyCoat', color: '#3e2d25' },
      { name: 'CallianasWand', color: '#252e2d' },
      { name: 'Vergesson', color: '#130b07' },
      { name: 'Waldhexe', color: '#342430' },
    ],
  },
  {
    paletteName: 'Caduceus Clay Colors',
    id: 'caduceus-clay-colors',
    emoji: '🍵',
    colors: [
      { name: 'PinkHair', color: '#c55f7b' },
      { name: 'Carapace', color: '#3acaa9' },
      { name: 'HotSpring', color: '#cceaf4' },
      { name: 'Commune', color: '#60d1d8' },
      { name: 'CrystalSeeds', color: '#a384c7' },
      { name: 'PieceOfHome', color: '#b3446e' },
      { name: 'Siblings', color: '#5f9088' },
      { name: 'DivineIntervention', color: '#a8b8c5' },
      { name: 'Mariner', color: '#2b3353' },
      { name: 'Xhorhaus', color: '#5a495e' },
      { name: 'FlorescentFungi', color: '#c34257' },
      { name: 'Residuum', color: '#266b58' },
      { name: 'SpeakWithDead', color: '#b7bcba' },
      { name: 'TreeSanctuary', color: '#3f4b3e' },
      { name: 'DustStoneAndClay', color: '#6b473a' },
      { name: 'Revivify', color: '#343f30' },
      { name: 'BloomingGrove', color: '#1d3433' },
      { name: 'DeadPeopleTea', color: '#5c625b' },
      { name: 'WildMother', color: '#1e342a' },
      { name: 'BackToTheSoil', color: '#3d2f26' },
    ],
  },
  {
    paletteName: 'Jester Lavorre Colors',
    id: 'jester-lavorre-colors',
    emoji: '🍭',
    colors: [
      { name: 'MoonweaversWrath', color: '#c1dcec' },
      { name: 'SpiritualWeapon', color: '#f69ef9' },
      { name: 'Lollipop', color: '#d9b7e2' },
      { name: 'DiamondTattoo', color: '#cdcdcf' },
      { name: 'TravelerCon', color: '#005700' },
      { name: 'LittleBlueTeifling', color: '#596d99' },
      { name: 'RubyOfTheSea', color: '#cb6880' },
      { name: 'Sending', color: '#af59a6' },
      { name: 'Pastry', color: '#a69186' },
      { name: 'TheTraveler', color: '#3f4a42' },
      { name: 'Nicodranas', color: '#425173' },
      { name: 'Cupcake', color: '#b15d6e' },
      { name: 'DustOfDeliciousness', color: '#543066' },
      { name: 'PaintsFromMomma', color: '#a57266' },
      { name: 'TuskLove', color: '#314339' },
      { name: 'Tusktooth', color: '#273d7c' },
      { name: 'TrickeryDomain', color: '#0d2856' },
      { name: 'Duplicity', color: '#2f204e' },
      { name: 'DetectiveAgency', color: '#281613' },
      { name: 'GreenCloak', color: '#183134' },
    ],
  },
  {
    paletteName: 'Beauregard Lionett Colors',
    id: 'beauregard-lionett-colors',
    emoji: '👊',
    colors: [
      { name: 'KiPoint', color: '#70c0b3' },
      { name: 'StunningStrike', color: '#52e4ff' },
      { name: 'LightningGloves', color: '#69717e' },
      { name: 'PopPop', color: '#785521' },
      { name: 'Kamordah', color: '#9a6479' },
      { name: 'JadeNecklace', color: '#526a46' },
      { name: 'FirstMate', color: '#1c3bce' },
      { name: 'GothWife', color: '#282c31' },
      { name: 'TJ', color: '#615140' },
      { name: 'EmpireKids', color: '#482528' },
      { name: 'ExtractAspects', color: '#4280ab' },
      { name: 'Notes', color: '#332316' },
      { name: 'FortuneTeller', color: '#4a2271' },
      { name: 'CobaltSoul', color: '#01279a' },
      { name: 'Dairon', color: '#211219' },
      { name: 'FlurryOfBlows', color: '#1d5289' },
      { name: 'BeausBo', color: '#1d1914' },
      { name: 'Molly', color: '#53395d' },
      { name: 'Expositor', color: '#171c5e' },
      { name: 'Zenoth', color: '#152a35' },
    ],
  },
  {
    paletteName: 'Yasha Nydoorin Colors',
    id: 'yasha-nydoorin-colors',
    emoji: '🌩️',
    colors: [
      { name: 'Flying', color: '#e9e8ed' },
      { name: 'MagiciansJudge', color: '#b7b6bd' },
      { name: 'StartOver', color: '#b6c4db' },
      { name: 'CircusFriend', color: '#1c0449' },
      { name: 'AngelOfIrons', color: '#5a5862' },
      { name: 'Chained', color: '#9b959d' },
      { name: 'StormLord', color: '#737279' },
      { name: 'Zuala', color: '#596484' },
      { name: 'Oban', color: '#1e061e' },
      { name: 'Worthy', color: '#4c4d58' },
      { name: 'RecklessAttack', color: '#303238' },
      { name: 'Wings', color: '#242426' },
      { name: 'Sentinel', color: '#27447f' },
      { name: 'Rage', color: '#1a1527' },
      { name: 'Purpose', color: '#2e3139' },
      { name: 'LaughingHand', color: '#17161b' },
      { name: 'OrphanMaker', color: '#1c1814' },
      { name: 'LostMemories', color: '#17212c' },
      { name: 'Charmed', color: '#151520' },
      { name: 'BrokenChains', color: '#0b0d0f' },
    ],
  },
  {
    paletteName: 'Veth Brenatto Colors',
    id: 'veth-brennato-colors',
    emoji: '🏹',
    colors: [
      { name: 'BrenattosVoltaicBolt', color: '#d2d2e4' },
      { name: 'Luc', color: '#99c5e6' },
      { name: 'CaseClosed', color: '#76b3a6' },
      { name: 'Trinkets', color: '#d2b63d' },
      { name: 'WorkingMom', color: '#d599e6' },
      { name: 'PorcelainMask', color: '#9ea19b' },
      { name: 'CharismaTattoo', color: '#00ffe9' },
      { name: 'Nott', color: '#495246' },
      { name: 'SettlingDown', color: '#c39a26' },
      { name: 'TrashWizard', color: '#981914' },
      { name: 'CrossbowExpert', color: '#362e2a' },
      { name: 'StealthCheck', color: '#6d757b' },
      { name: 'UncannyDodge', color: '#243c1b' },
      { name: 'Buttons', color: '#cc9a29' },
      { name: 'Antlers', color: '#966a52' },
      { name: 'SneakAttack', color: '#242625' },
      { name: 'ChaosCrew', color: '#25111c' },
      { name: 'Goblin', color: '#262c17' },
      { name: 'Transformation', color: '#b8762f' },
      { name: 'Yeza', color: '#493231' },
    ],
  },
  {
    paletteName: 'Fjord Stone Colors',
    id: 'fjord-stone-colors',
    emoji: '🌊',
    colors: [
      { name: 'SwordOfFathoms', color: '#f7f1e3' },
      { name: 'StarRazor', color: '#7a99aa' },
      { name: 'Consume', color: '#ddcf3a' },
      { name: 'PortDumali', color: '#275850' },
      { name: 'Avantika', color: '#5f1b29' },
      { name: 'TheStoneFamily', color: '#7f7682' },
      { name: 'Jester', color: '#2562a5' },
      { name: 'Melora', color: '#40573f' },
      { name: 'OathOfTheOpenSea', color: '#2b4648' },
      { name: 'IronShepherds', color: '#401120' },
      { name: 'MarineLayer', color: '#57595b' },
      { name: 'Captain', color: '#305a6d' },
      { name: 'NotEasyBeingGreen', color: '#394e3c' },
      { name: 'Orly', color: '#203d3e' },
      { name: 'Soltryce', color: '#2f080a' },
      { name: 'TexBlade', color: '#0c0b0e' },
      { name: 'EldritchBlast', color: '#1c1425' },
      { name: 'DivineSense', color: '#243b28' },
      { name: 'TheHardDecisions', color: '#2b1f23' },
      { name: 'Vandren', color: '#2d1e21' },
    ],
  },
  {
    paletteName: 'Mollymauk Tealeaf Colors',
    id: 'mollymauk-tealeaf-colors',
    emoji: '🎭',
    colors: [
      { name: 'PutItBack', color: '#8b7fc5' },
      { name: 'Moonweaver', color: '#c5e1df' },
      { name: 'TarotCards', color: '#592542' },
      { name: 'SummersDance', color: '#dfd9d0' },
      { name: 'Tombtakers', color: '#674a52' },
      { name: 'CircusMan', color: '#7e6fa1' },
      { name: 'FletchingAndMoondrop', color: '#66757b' },
      { name: 'ViciousMockery', color: '#49223d' },
      { name: 'Kingsley', color: '#bf9e32' },
      { name: 'Lorenzo', color: '#52312c' },
      { name: 'Lucien', color: '#5f5d95' },
      { name: 'Peacock', color: '#2ac3b8' },
      { name: 'BloodHunter', color: '#4c162b' },
      { name: 'Nonagon', color: '#a73040' },
      { name: 'EmptyGrave', color: '#3a2e25' },
      { name: 'Angel', color: '#130c17' },
      { name: 'BetterThanYouFoundIt', color: '#25738e' },
      { name: 'HellishRebuke', color: '#3f172b' },
      { name: 'NineEyes', color: '#db1717' },
      { name: 'Cree', color: '#211b14' },
    ],
  },
  {
    paletteName: 'Essek Thelyss Colors',
    id: 'essek-thelyss-colors',
    emoji: '💠',
    colors: [
      { name: 'Luxon', color: '#aec0dc' },
      { name: 'TeleportTaxi', color: '#8182af' },
      { name: 'Trent', color: '#96a7b4' },
      { name: 'Beacon', color: '#9a9ba4' },
      { name: 'Regret', color: '#6b6685' },
      { name: 'FortunesFavor', color: '#533ee5' },
      { name: 'Bazzoxan', color: '#524877' },
      { name: 'MagnifyGravity', color: '#353454' },
      { name: 'FragmentOfPossibility', color: '#71717e' },
      { name: 'Verin', color: '#4a3e6d' },
      { name: 'DarkStar', color: '#223981' },
      { name: 'Drow', color: '#3d355a' },
      { name: 'Unconsecuted', color: '#382748' },
      { name: 'Xhorhas', color: '#14121c' },
      { name: 'HotBoi', color: '#311069' },
      { name: 'WarCriminal', color: '#14142f' },
      { name: 'RavenousVoid', color: '#1e1622' },
      { name: 'Shadowghast', color: '#351227' },
      { name: 'Shadowhand', color: '#0a0a0f' },
      { name: 'ResonantEcho', color: '#1a1235' },
    ],
  },
];

export default seedColors;
